package com.ludoroyale.app.store

import android.content.Context
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class StoreCategory { TOKEN_SKIN, DICE_SKIN, BOARD_THEME, AVATAR, PROFILE_FRAME }
data class StoreItem(val id:String,val name:String,val description:String,val category:StoreCategory,val preview:String,val price:Int)
data class WalletTransaction(val id:String,val amount:Int,val reason:String,val timestamp:Long=System.currentTimeMillis())
data class WalletState(val coins:Int=2480,val owned:Set<String> = setOf("token_classic","dice_classic","board_classic","avatar_classic","frame_classic"),val equipped:Map<StoreCategory,String> = emptyMap(),val transactions:List<WalletTransaction> = emptyList())
object RewardAmounts { const val DAILY_COIN_BONUS=100; const val MISSION_COIN_BONUS=100; const val MATCH_COMPLETE=40; const val VICTORY=120; const val LEVEL_UP=250 }
object StoreCatalog { val items=listOf(StoreItem("token_classic","Classic Tokens","The original royal set",StoreCategory.TOKEN_SKIN,"●",0),StoreItem("token_sunset","Sunset Tokens","Warm coral and gold",StoreCategory.TOKEN_SKIN,"●",450),StoreItem("token_ocean","Ocean Tokens","Cool blue finish",StoreCategory.TOKEN_SKIN,"●",650),StoreItem("dice_classic","Classic Dice","Clean ivory dice",StoreCategory.DICE_SKIN,"◆",0),StoreItem("dice_royal","Royal Dice","A deep violet finish",StoreCategory.DICE_SKIN,"◆",500),StoreItem("board_classic","Classic Board","The Ludo Royale table",StoreCategory.BOARD_THEME,"▦",0),StoreItem("board_twilight","Twilight Board","A midnight royal table",StoreCategory.BOARD_THEME,"▦",900),StoreItem("avatar_classic","Classic Avatar","Your default avatar",StoreCategory.AVATAR,"◎",0),StoreItem("avatar_crown","Crown Avatar","A little extra royalty",StoreCategory.AVATAR,"♛",400),StoreItem("frame_classic","Classic Frame","A clean profile frame",StoreCategory.PROFILE_FRAME,"◇",0),StoreItem("frame_gold","Gold Frame","A bright profile frame",StoreCategory.PROFILE_FRAME,"◈",600));fun item(id:String)=items.first{it.id==id}}
class WalletRepository(context:Context){private val p=context.getSharedPreferences("wallet_store",Context.MODE_PRIVATE);fun load():WalletState{val owned=p.getStringSet("owned",null)?.toSet()?:setOf("token_classic","dice_classic","board_classic","avatar_classic","frame_classic");val equipped=StoreCategory.entries.mapNotNull{c->p.getString("equipped_${c.name}",null)?.let{c to it}}.toMap();return WalletState(p.getInt("coins",2480),owned,equipped)};fun save(s:WalletState){val e=p.edit().putInt("coins",s.coins).putStringSet("owned",s.owned);s.equipped.forEach{(c,id)->e.putString("equipped_${c.name}",id)};e.apply()}}
class WalletViewModel(private val repo:WalletRepository):androidx.lifecycle.ViewModel(){private val _wallet=MutableStateFlow(repo.load());val wallet:StateFlow<WalletState>=_wallet.asStateFlow();private fun update(s:WalletState){repo.save(s);_wallet.value=s};fun earn(amount:Int,reason:String):Boolean{if(amount<=0)return false;val w=_wallet.value;update(w.copy(coins=w.coins+amount,transactions=(w.transactions+WalletTransaction("earn_${System.nanoTime()}",amount,reason)).takeLast(100)));return true};fun purchase(id:String):Boolean{val item=StoreCatalog.items.firstOrNull{it.id==id}?:return false;val w=_wallet.value;if(item.id in w.owned||item.price<0||w.coins<item.price)return false;update(w.copy(coins=w.coins-item.price,owned=w.owned+item.id,transactions=(w.transactions+WalletTransaction("buy_${item.id}_${System.nanoTime()}",-item.price,"Store purchase: ${item.name}")).takeLast(100)));return true};fun equip(id:String):Boolean{val item=StoreCatalog.items.firstOrNull{it.id==id}?:return false;if(id !in _wallet.value.owned)return false;update(_wallet.value.copy(equipped=_wallet.value.equipped+ (item.category to id)));return true};fun unequip(category:StoreCategory){update(_wallet.value.copy(equipped=_wallet.value.equipped-category))}}
