package com.ludoroyale.app.online

import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.tasks.await

interface OnlineRepository { suspend fun signInGuest():OnlineResult<OnlinePlayer>; suspend fun createRoom(host:OnlinePlayer,capacity:Int):OnlineResult<OnlineRoom>; suspend fun joinRoom(code:String,player:OnlinePlayer):OnlineResult<OnlineRoom>; suspend fun leaveRoom(code:String,playerId:String):OnlineResult<Unit>; suspend fun searchPlayer(playerId:String):OnlineResult<OnlinePlayer?> }
class FirebaseOnlineRepository(private val auth:FirebaseAuth=FirebaseAuth.getInstance(),private val db:FirebaseFirestore=FirebaseFirestore.getInstance()):OnlineRepository{
 override suspend fun signInGuest():OnlineResult<OnlinePlayer> = try { val result=auth.signInAnonymously().await(); val id=result.user?.uid ?: return OnlineResult.Failure("Authentication failed"); OnlineResult.Success(OnlinePlayer(id,"Guest ${id.take(6)}")) } catch(e:Exception){OnlineResult.Failure("Connection unavailable")}
 override suspend fun createRoom(host:OnlinePlayer,capacity:Int):OnlineResult<OnlineRoom> = try { val code=(100000..999999).random().toString(); val room=OnlineRoom(code,host.playerId,listOf(host),capacity); db.collection("rooms").document(code).set(room).await(); OnlineResult.Success(room) } catch(e:Exception){OnlineResult.Failure("Could not create room")}
 override suspend fun joinRoom(code:String,player:OnlinePlayer):OnlineResult<OnlineRoom> = try { val ref=db.collection("rooms").document(code); val snap=ref.get().await(); val room=snap.toObject(OnlineRoom::class.java)?:return OnlineResult.Failure("Room not found"); if(room.state!=RoomState.WAITING)return OnlineResult.Failure("Game already started"); if(room.isFull)return OnlineResult.Failure("Room is full"); val updated=room.copy(players=room.players+player); ref.set(updated).await(); OnlineResult.Success(updated) } catch(e:Exception){OnlineResult.Failure("Connection lost")}
 override suspend fun leaveRoom(code:String,playerId:String):OnlineResult<Unit> = try { db.collection("rooms").document(code).update("players",emptyList<OnlinePlayer>()).await(); OnlineResult.Success(Unit) } catch(e:Exception){OnlineResult.Failure("Could not leave room")}
 override suspend fun searchPlayer(playerId:String):OnlineResult<OnlinePlayer?> = try { OnlineResult.Success(db.collection("players").document(playerId).get().await().toObject(OnlinePlayer::class.java)) } catch(e:Exception){OnlineResult.Failure("Request failed")}
}
class OfflineOnlineRepository:OnlineRepository{override suspend fun signInGuest()=OnlineResult.Success(OnlinePlayer("guest-local","Local Guest"));override suspend fun createRoom(host:OnlinePlayer,capacity:Int)=OnlineResult.Success(OnlineRoom("LOCAL",host.playerId,listOf(host),capacity));override suspend fun joinRoom(code:String,player:OnlinePlayer)=OnlineResult.Failure("Online connection unavailable");override suspend fun leaveRoom(code:String,playerId:String)=OnlineResult.Success(Unit);override suspend fun searchPlayer(playerId:String)=OnlineResult.Success(null)}

interface AccountRepository { suspend fun register(email:String,password:String,username:String):OnlineResult<OnlinePlayer>; suspend fun login(email:String,password:String):OnlineResult<OnlinePlayer>; suspend fun deleteAccount():OnlineResult<Unit>; fun logout() }
class FirebaseAccountRepository(private val auth:FirebaseAuth=FirebaseAuth.getInstance()):AccountRepository { override suspend fun register(email:String,password:String,username:String)=try{val r=auth.createUserWithEmailAndPassword(email,password).await();OnlineResult.Success(OnlinePlayer(r.user!!.uid,username))}catch(e:Exception){OnlineResult.Failure("Registration failed")};override suspend fun login(email:String,password:String)=try{val r=auth.signInWithEmailAndPassword(email,password).await();OnlineResult.Success(OnlinePlayer(r.user!!.uid,"Player ${r.user!!.uid.take(6)}"))}catch(e:Exception){OnlineResult.Failure("Login failed")};override suspend fun deleteAccount()=try{auth.currentUser?.delete()?.await();OnlineResult.Success(Unit)}catch(e:Exception){OnlineResult.Failure("Account deletion failed")};override fun logout(){auth.signOut()} }
