package com.ludoroyale.app.milestones
import android.content.Context
import com.ludoroyale.app.progression.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class MilestoneCategory{GAMEPLAY,WINS,CAPTURES,TOKENS,PROGRESSION,MULTIPLAYER,COLLECTION,SPECIAL}
data class Milestone(val id:String,val category:MilestoneCategory,val name:String,val description:String,val icon:String,val target:Int,val progress:Int,val rewardCoins:Int,val rewardXp:Int,val completed:Boolean,val claimed:Boolean=false,val completedAt:Long?=null)
object MilestoneCatalog{fun all(p:PlayerProgress)=listOf(Milestone("play1",MilestoneCategory.GAMEPLAY,"First game","Complete your first match","✦",1,p.games,100,30,p.games>=1),Milestone("play10",MilestoneCategory.GAMEPLAY,"Regular","Play 10 matches","★",10,p.games,250,70,p.games>=10),Milestone("win1",MilestoneCategory.WINS,"First victory","Win your first match","♛",1,p.wins,150,50,p.wins>=1),Milestone("win10",MilestoneCategory.WINS,"Ten crowns","Win 10 matches","♕",10,p.wins,400,120,p.wins>=10),Milestone("capture10",MilestoneCategory.CAPTURES,"Hunter","Capture 10 tokens","◉",10,p.captures,300,80,p.captures>=10),Milestone("home25",MilestoneCategory.TOKENS,"Token master","Bring 25 tokens home","◆",25,p.tokensHome,500,150,p.tokensHome>=25),Milestone("level10",MilestoneCategory.PROGRESSION,"Royal legend","Reach level 10","♜",10,p.level,600,200,p.level>=10),Milestone("collect5",MilestoneCategory.COLLECTION,"Collector","Collect 5 cosmetics","◇",5,0,250,80,false))}
class MilestoneRepository(context:Context){private val p=context.getSharedPreferences("milestones",Context.MODE_PRIVATE);fun claimed(id:String)=p.getBoolean("claimed_$id",false);fun claim(id:String){p.edit().putBoolean("claimed_$id",true).apply()};fun badge()=p.getString("badge",null);fun setBadge(id:String?)=p.edit().putString("badge",id).apply()}
class MilestoneManager(private val repo:MilestoneRepository){fun list(p:PlayerProgress)=MilestoneCatalog.all(p).map{it.copy(claimed=repo.claimed(it.id))};fun claim(m:Milestone):Boolean{if(!m.completed||m.claimed)return false;repo.claim(m.id);return true};fun setBadge(m:Milestone){if(m.completed)repo.setBadge(m.id)}}
class MilestoneViewModel(private val repo:MilestoneRepository):androidx.lifecycle.ViewModel(){private val _items=MutableStateFlow<List<Milestone>>(emptyList());val items=_items.asStateFlow();private val _selected=MutableStateFlow<String?>(repo.badge());val selectedBadge=_selected.asStateFlow();fun refresh(p:PlayerProgress){_items.value=MilestoneManager(repo).list(p)};fun claim(m:Milestone)=MilestoneManager(repo).claim(m);fun selectBadge(m:Milestone){MilestoneManager(repo).setBadge(m);_selected.value=m.id}}
